const mongoose =require("mongoose");
const Joi = require("joi");
const jwt = require("jsonwebtoken");

const questionSchema = new mongoose.Schema({
    userId: String,
    1:String,
    2:Array,
    3:String,
    4:String,
    5:String,
    6:Date,
    7:String,
    8:String,
    9:Date,
    10:String,
    11:Array,
    12:String,
    13:Array,
    14:String,
    15:Array,
    16:String,
    17:Date,
    18:Array,
    19:String,
    20:String,
    21:String,
    22:Array,
    23:Array, 
    24:String,
    25:String,
    26:String, 
    27:String,
    28:String,
    29:String,
    30:String,
    31:String,
    32:String,
    33:String,
    34:String,
    35:String,
    36:String,
    37:String,
    38:String,
    39:String,
    40:String,
    41:String,
    42:String,
    43:String,
    44:Date,
    45:String,
    46:Array,
    47:String,
    48:Array,
    49:String,
    date_created: { type: Date, default: Date.now() },
    finished: { type: Boolean, default: false },
});

exports.QuestionModel = mongoose.model("questions", questionSchema);

// exports.validQuestion = (_bodyData) => {
//     let joiSchema = Joi.object({
//         1: Joi.string().min(1).max(99).required(),
//         2: Joi.string().min(1).max(99).required(),
//         3: Joi.string().min(1).max(99).required(),
//         4: Joi.string().min(1).max(99).required(),
//         5: Joi.string().min(1).max(99).required(),
//         6: Joi.date().required(),
//         7: Joi.string().min(1).max(99).required(),
//         8: Joi.string().min(1).max(99).required(),
//         9: Joi.date().required(),
//         10: Joi.string().min(1).max(99).required(),
//         11: Joi.string().min(1).max(99).required(),
//         12: Joi.string().min(1).max(99).required(),
//         13: Joi.string().min(1).max(99).required(),
//         14: Joi.string().min(1).max(99).required(),
//         15: Joi.string().min(1).max(99).required(),
//         16: Joi.string().min(1).max(99).required(),
//         17: Joi.date().required(),
//         18: Joi.string().min(1).max(99).required(),
//         19: Joi.string().min(1).max(99).required(),
//         20: Joi.string().min(1).max(99).required(),
//         21: Joi.string().min(1).max(99).required(),
//         22: Joi.string().min(1).max(99).required(),
//         23: Joi.string().min(1).max(99).required(),
//         24: Joi.string().min(1).max(99).required(),
//         25: Joi.string().min(1).max(99).required(),
//         26: Joi.string().min(1).max(99).required(),
//         27: Joi.string().min(1).max(99).required(),
//         28: Joi.string().min(1).max(99).required(),
//         29: Joi.string().min(1).max(99).required(),
//         30: Joi.string().min(1).max(99).required(),
//         31: Joi.string().min(1).max(99).required(),
//         32: Joi.string().min(1).max(99).required(), 
//         33: Joi.string().min(1).max(99).required(),
//         34: Joi.string().min(1).max(99).required(),
//         35: Joi.string().min(1).max(99).required(),
//         36: Joi.string().min(1).max(99).required(),
//         37: Joi.string().min(1).max(99).required(),
//         38: Joi.string().min(1).max(99).required(),
//         39: Joi.string().min(1).max(99).required(),
//         40: Joi.string().min(1).max(99).required(),
//         41: Joi.string().min(1).max(99).required(),
//         42: Joi.string().min(1).max(99).required(),
//         43: Joi.string().min(1).max(99).required(),
//         44: Joi.date().required(),
//         45: Joi.string().min(1).max(99).required(),
//         46: Joi.string().min(1).max(99).required(),
//         47: Joi.string().min(1).max(99).required(),
//         48: Joi.string().min(1).max(99).required(),
//         49: Joi.string().min(1).max(99).required(),
//     });

//     return joiSchema.validate(_bodyData);
// };
