const mongoose =require("mongoose");
const Joi = require("joi");
const jwt = require("jsonwebtoken");

const questionSchema = new mongoose.Schema({
    userId: String,
    1: String,
    2: String,
    3: Date,
    4: String,
    5: [String],
    6: String,
    7: String,
    8: String,
    9: Date,
    10: String,
    11: String,
    12: Date,
    13: String,
    14: [String],
    15: String,
    16: [String],
    17: String,
    18: [String],
    19: String,
    20: Date,
    21: [String],
    22: String,
    23: String,
    24: String,
    25: [String],
    26: [String],
    27: String,
    28: String,
    29: String,
    30: String,
    31: String,
    32: String,
    33: String,
    34: String,
    35: String,
    36: String,
    37: String,
    38: String,
    39: String,
    40: String,
    41: String,
    42: [String],
    43: [String],
    44: String,
    45: String,
    46: String,
    47: String,
    48: Date,
    49: String,
    50: [String],
    51: String,
    52: [String],
    53: String,
    54: String,
    55: String,
    date_created: { type: Date, default: Date.now() },
    section: String,
    finished: { type: Boolean, default: false },
});

exports.QuestionModel = mongoose.model("questions", questionSchema);

