const mongoose =require("mongoose");
const Joi = require("joi");
const jwt = require("jsonwebtoken");

const questionSchema = new mongoose.Schema({
    userId: String,
    1:String,
    2:Array,
    3:String,
    4:String,
    5:String,
    6:Date,
    7:String,
    8:String,
    9:Date,
    10:String,
    11:Array,
    12:String,
    13:Array,
    14:String,
    15:Array,
    16:String,
    17:Date,
    18:Array,
    19:String,
    20:String,
    21:String,
    22:Array,
    23:Array, 
    24:String,
    25:String,
    26:String, 
    27:String,
    28:String,
    29:String,
    30:String,
    31:String,
    32:String,
    33:String,
    34:String,
    35:String,
    36:String,
    37:String,
    38:String,
    39:String,
    40:String,
    41:String,
    42:String,
    43:String,
    44:Date,
    45:String,
    46:Array,
    47:String,
    48:Array,
    49:String,
    date_created: { type: Date, default: Date.now() },
    section: String,
    finished: { type: Boolean, default: false },
});

exports.QuestionModel = mongoose.model("questions", questionSchema);

